name=[
    '阿部寛',
    'Google',
    'Yahoo Japan',
    'Youtube',
    'Amazon',
    'JSTORM 嵐',
    'twitter',
    'Apple',
    'ホロライブプロダクション',
    'にじさんじ公式サイト',
    'テスラ日本語版サイト',
    'トヨタ自動車',
    'ニコニコ動画',
    '任天堂',
    'Cygames',
    'ウマ娘',
    'プリンセスコネクト Re:Dive',
    'AEON',
    'Pixiv',
    'Starbucks japan',
    'Github',
    'スピッツ',
    'Mr.Children',
    'Instagram',
    'ヨルシカ',
    'Walmart',
    'Microsoft 日本語サイト',
    '米津玄師',
    'ずっと真夜中でいいのに。',
    '首相官邸ホームページ'
]